// packages/angular-cli/src/lib/cli-panel/cli-panel.component.ts
import {
    Component,
    ElementRef,
    EventEmitter,
    HostListener,
    Input,
    Output,
    QueryList,
    ViewChild,
    ViewChildren,
} from '@angular/core';
import {
    CliPanelConfig,
    ICliCommandProcessor,
    ICliModule,
} from '@qodalis/cli-core';
import { CliEngineOptions } from '@qodalis/cli';
import { CliComponent } from '../cli/cli.component';
import { CollapsableContentComponent } from '../collapsable-content/collapsable-content.component';

export interface TerminalPane {
    id: number;
    widthPercent: number;
}

export interface TerminalTab {
    id: number;
    title: string;
    isEditing: boolean;
    panes: TerminalPane[];
}

export interface TabContextMenu {
    visible: boolean;
    x: number;
    y: number;
    tabId: number;
}

export type CliPanelOptions = CliEngineOptions & CliPanelConfig;

/**
 * A component that displays the CLI on the bottom of page.
 */
@Component({
    selector: 'cli-panel',
    templateUrl: './cli-panel.component.html',
    styleUrls: ['./cli-panel.component.sass'],
})
export class CliPanelComponent {
    /**
     * The options for the CLI.
     */
    @Input() options?: CliPanelOptions;

    /**
     * Optional list of CLI modules to register with each terminal pane.
     */
    @Input() modules?: ICliModule[];

    /**
     * Optional list of command processors to register with each terminal pane.
     * This allows passing processors without Angular DI (framework-agnostic pattern).
     * @deprecated Use modules instead.
     */
    @Input() processors?: ICliCommandProcessor[];

    @Output() onClose = new EventEmitter<void>();

    @ViewChild(CollapsableContentComponent)
    collapsableContent!: CollapsableContentComponent;
    @ViewChildren(CliComponent) cliComponents!: QueryList<CliComponent>;

    visible = true;

    tabs: TerminalTab[] = [];
    activeTabId = 0;
    activePaneId = 0;
    private nextTabId = 1;
    private nextPaneId = 1;

    contextMenu: TabContextMenu = {
        visible: false,
        x: 0,
        y: 0,
        tabId: 0,
    };

    paneResizing = false;
    private paneResizeTabId = 0;
    private paneResizeDividerIndex = 0;
    private paneResizeStartX = 0;
    private paneResizeStartWidths: number[] = [];
    private paneResizeContainerWidth = 0;

    private static readonly MIN_PANE_WIDTH_PERCENT = 10;

    protected terminalHeight: string = '100%';

    protected initialized: boolean = false;

    constructor(private readonly elementRef: ElementRef) {}

    @HostListener('document:click', ['$event'])
    onDocumentClick(event: MouseEvent): void {
        if (this.contextMenu.visible) {
            this.closeContextMenu();
        }
    }

    @HostListener('document:keydown.escape')
    onEscapeKey(): void {
        if (this.contextMenu.visible) {
            this.closeContextMenu();
        }
        this.cancelAllEditing();
    }

    onToggle($event: boolean) {
        if (!$event && !this.initialized) {
            this.initialized = true;
            this.addTab();
        }
    }

    onContentSizeChange(_event: number) {
        // Terminal height is handled via CSS flex layout
    }

    // --- Tab management ---

    addTab(): void {
        const pane: TerminalPane = { id: this.nextPaneId++, widthPercent: 100 };
        const tab: TerminalTab = {
            id: this.nextTabId++,
            title: `Terminal ${this.nextTabId - 1}`,
            isEditing: false,
            panes: [pane],
        };
        this.tabs.push(tab);
        this.activeTabId = tab.id;
        this.activePaneId = pane.id;
    }

    closeTab(id: number): void {
        const index = this.tabs.findIndex((t) => t.id === id);
        if (index === -1) return;

        this.tabs.splice(index, 1);

        if (this.tabs.length === 0) {
            this.initialized = false;
            this.collapsableContent?.toggleTerminal();
            return;
        }

        if (this.activeTabId === id) {
            const nextIndex = Math.min(index, this.tabs.length - 1);
            this.selectTab(this.tabs[nextIndex].id);
        }
    }

    selectTab(id: number): void {
        this.activeTabId = id;
        const tab = this.findTab(id);
        if (tab && tab.panes.length > 0) {
            this.activePaneId = tab.panes[0].id;
        }
        setTimeout(() => {
            this.focusActiveTerminal();
        });
    }

    trackByTabId(_index: number, tab: TerminalTab): number {
        return tab.id;
    }

    trackByPaneId(_index: number, pane: TerminalPane): number {
        return pane.id;
    }

    // --- Inline rename ---

    startRename(tab: TerminalTab): void {
        this.cancelAllEditing();
        tab.isEditing = true;
        setTimeout(() => {
            const input = this.elementRef.nativeElement.querySelector(
                '.tab-rename-input',
            ) as HTMLInputElement | null;
            if (input) {
                input.focus();
                input.select();
            }
        });
    }

    onTabDoubleClick(tab: TerminalTab): void {
        this.startRename(tab);
    }

    commitRename(tab: TerminalTab, value: string): void {
        const trimmed = value.trim();
        if (trimmed) {
            tab.title = trimmed;
        }
        tab.isEditing = false;
    }

    onRenameKeydown(event: KeyboardEvent, tab: TerminalTab): void {
        if (event.key === 'Enter') {
            this.commitRename(tab, (event.target as HTMLInputElement).value);
        } else if (event.key === 'Escape') {
            tab.isEditing = false;
        }
    }

    onRenameBlur(event: FocusEvent, tab: TerminalTab): void {
        if (tab.isEditing) {
            this.commitRename(tab, (event.target as HTMLInputElement).value);
        }
    }

    // --- Context menu ---

    onTabContextMenu(event: MouseEvent, tab: TerminalTab): void {
        event.preventDefault();
        event.stopPropagation();

        this.contextMenu = {
            visible: true,
            x: event.clientX,
            y: event.clientY,
            tabId: tab.id,
        };
    }

    closeContextMenu(): void {
        this.contextMenu = { ...this.contextMenu, visible: false };
    }

    contextMenuRename(): void {
        const tab = this.findTab(this.contextMenu.tabId);
        this.closeContextMenu();
        if (tab) {
            this.startRename(tab);
        }
    }

    contextMenuDuplicate(): void {
        const sourceTab = this.findTab(this.contextMenu.tabId);
        this.closeContextMenu();
        if (sourceTab) {
            const pane: TerminalPane = {
                id: this.nextPaneId++,
                widthPercent: 100,
            };
            const tab: TerminalTab = {
                id: this.nextTabId++,
                title: `${sourceTab.title} (copy)`,
                isEditing: false,
                panes: [pane],
            };
            const sourceIndex = this.tabs.indexOf(sourceTab);
            this.tabs.splice(sourceIndex + 1, 0, tab);
            this.activeTabId = tab.id;
            this.activePaneId = pane.id;
        }
    }

    contextMenuClose(): void {
        const id = this.contextMenu.tabId;
        this.closeContextMenu();
        this.closeTab(id);
    }

    contextMenuCloseOthers(): void {
        const id = this.contextMenu.tabId;
        this.closeContextMenu();
        this.tabs = this.tabs.filter((t) => t.id === id);
        this.activeTabId = id;
    }

    contextMenuCloseToTheRight(): void {
        const id = this.contextMenu.tabId;
        this.closeContextMenu();
        const index = this.tabs.findIndex((t) => t.id === id);
        if (index === -1) return;
        this.tabs = this.tabs.slice(0, index + 1);
        if (!this.tabs.find((t) => t.id === this.activeTabId)) {
            this.activeTabId = id;
        }
    }

    contextMenuCloseAll(): void {
        this.closeContextMenu();
        this.tabs = [];
        this.initialized = false;
        this.collapsableContent?.toggleTerminal();
    }

    // --- Split / close pane ---

    splitRight(tabId?: number, afterPaneId?: number): void {
        const tab = this.findTab(tabId ?? this.activeTabId);
        if (!tab) return;

        const targetPaneId = afterPaneId ?? this.activePaneId;
        const paneIndex = tab.panes.findIndex((p) => p.id === targetPaneId);
        const insertIndex = paneIndex === -1 ? tab.panes.length : paneIndex + 1;

        const newPane: TerminalPane = {
            id: this.nextPaneId++,
            widthPercent: 0,
        };
        tab.panes.splice(insertIndex, 0, newPane);

        const evenWidth = 100 / tab.panes.length;
        tab.panes.forEach((p) => (p.widthPercent = evenWidth));
        this.normalizePaneWidths(tab.panes);

        this.activePaneId = newPane.id;
    }

    closePane(tabId: number, paneId: number): void {
        const tab = this.findTab(tabId);
        if (!tab) return;

        if (tab.panes.length <= 1) {
            this.closeTab(tabId);
            return;
        }

        const index = tab.panes.findIndex((p) => p.id === paneId);
        if (index === -1) return;

        tab.panes.splice(index, 1);

        const totalRemaining = tab.panes.reduce(
            (s, p) => s + p.widthPercent,
            0,
        );
        if (totalRemaining > 0) {
            tab.panes.forEach((p) => {
                p.widthPercent = (p.widthPercent / totalRemaining) * 100;
            });
        }
        this.normalizePaneWidths(tab.panes);

        if (this.activePaneId === paneId) {
            const newIndex = Math.min(index, tab.panes.length - 1);
            this.activePaneId = tab.panes[newIndex].id;
        }

        setTimeout(() => this.focusActiveTerminal());
    }

    contextMenuSplitRight(): void {
        const tabId = this.contextMenu.tabId;
        this.closeContextMenu();
        this.splitRight(tabId);
    }

    // --- Pane resize ---

    onPaneResizeStart(
        event: MouseEvent,
        tabId: number,
        dividerIndex: number,
    ): void {
        event.preventDefault();
        const tab = this.findTab(tabId);
        if (!tab) return;

        this.paneResizing = true;
        this.paneResizeTabId = tabId;
        this.paneResizeDividerIndex = dividerIndex;
        this.paneResizeStartX = event.clientX;
        this.paneResizeStartWidths = tab.panes.map((p) => p.widthPercent);

        const container = (event.target as HTMLElement).closest(
            '.terminal-panes-container',
        );
        this.paneResizeContainerWidth = container ? container.clientWidth : 1;

        document.body.classList.add('cli-pane-resizing');
    }

    @HostListener('document:mousemove', ['$event'])
    onPaneResizeMove(event: MouseEvent): void {
        if (!this.paneResizing) return;

        const tab = this.findTab(this.paneResizeTabId);
        if (!tab) return;

        const deltaX = event.clientX - this.paneResizeStartX;
        const deltaPct = (deltaX / this.paneResizeContainerWidth) * 100;

        const i = this.paneResizeDividerIndex;
        const minW = CliPanelComponent.MIN_PANE_WIDTH_PERCENT;

        let leftWidth = this.paneResizeStartWidths[i] + deltaPct;
        let rightWidth = this.paneResizeStartWidths[i + 1] - deltaPct;

        if (leftWidth < minW) {
            leftWidth = minW;
            rightWidth =
                this.paneResizeStartWidths[i] +
                this.paneResizeStartWidths[i + 1] -
                minW;
        }
        if (rightWidth < minW) {
            rightWidth = minW;
            leftWidth =
                this.paneResizeStartWidths[i] +
                this.paneResizeStartWidths[i + 1] -
                minW;
        }

        tab.panes[i].widthPercent = leftWidth;
        tab.panes[i + 1].widthPercent = rightWidth;
    }

    @HostListener('document:mouseup')
    onPaneResizeEnd(): void {
        if (!this.paneResizing) return;
        this.paneResizing = false;
        document.body.classList.remove('cli-pane-resizing');
    }

    // --- Pane focus ---

    onPaneClick(tabId: number, paneId: number): void {
        this.activePaneId = paneId;
        if (this.activeTabId !== tabId) {
            this.activeTabId = tabId;
        }
        setTimeout(() => this.focusPane(tabId, paneId));
    }

    // --- Helpers ---

    private findTab(id: number): TerminalTab | undefined {
        return this.tabs.find((t) => t.id === id);
    }

    private cancelAllEditing(): void {
        this.tabs.forEach((t) => (t.isEditing = false));
    }

    private focusActiveTerminal(): void {
        this.focusPane(this.activeTabId, this.activePaneId);
    }

    private focusPane(tabId: number, paneId: number): void {
        if (!this.cliComponents) return;

        let flatIndex = 0;
        for (const tab of this.tabs) {
            for (const pane of tab.panes) {
                if (tab.id === tabId && pane.id === paneId) {
                    const component = this.cliComponents.toArray()[flatIndex];
                    component?.focus();
                    return;
                }
                flatIndex++;
            }
        }
    }

    private normalizePaneWidths(panes: TerminalPane[]): void {
        const total = panes.reduce((s, p) => s + p.widthPercent, 0);
        if (total === 0) return;
        const scale = 100 / total;
        panes.forEach((p) => (p.widthPercent = p.widthPercent * scale));
    }
}

<collapsable-content
  [isCollapsed]="options?.isCollapsed ?? true"
  [position]="options?.position ?? 'bottom'"
  [closable]="options?.closable ?? true"
  [resizable]="options?.resizable ?? true"
  (onToggle)="onToggle($event)"
  (onContentSizeChange)="onContentSizeChange($event)"
  (onClose)="onClose.emit()"
  *ngIf="visible"
>
  <ng-container *ngIf="initialized">
    <div class="terminal-tabs">
      <ul class="tab-list">
        <li
          *ngFor="let tab of tabs; trackBy: trackByTabId"
          class="tab"
          [class.active]="tab.id === activeTabId"
          (click)="selectTab(tab.id)"
          (dblclick)="onTabDoubleClick(tab)"
          (contextmenu)="onTabContextMenu($event, tab)"
        >
          <input
            *ngIf="tab.isEditing"
            class="tab-rename-input"
            type="text"
            [value]="tab.title"
            (keydown)="onRenameKeydown($event, tab)"
            (blur)="onRenameBlur($event, tab)"
            (click)="$event.stopPropagation()"
            (dblclick)="$event.stopPropagation()"
            #renameInput
          />
          <span *ngIf="!tab.isEditing" class="tab-title">{{ tab.title }}</span>
          <button
            *ngIf="!tab.isEditing"
            class="close-btn"
            title="Close tab"
            (click)="closeTab(tab.id); $event.stopPropagation()"
          >
            &times;
          </button>
        </li>
      </ul>
      <button class="add-tab" title="New terminal" (click)="addTab()">+</button>
    </div>
    <div class="terminal-instances">
      <div
        *ngFor="let tab of tabs; trackBy: trackByTabId"
        class="terminal-instance"
        [hidden]="tab.id !== activeTabId"
      >
        <div
          class="terminal-panes-container"
          [attr.data-tab-id]="tab.id"
          [class.resizing]="paneResizing"
        >
          <ng-container
            *ngFor="
              let pane of tab.panes;
              let i = index;
              trackBy: trackByPaneId
            "
          >
            <div
              *ngIf="i > 0"
              class="pane-divider"
              (mousedown)="onPaneResizeStart($event, tab.id, i - 1)"
            >
              <div class="pane-divider-grip"></div>
            </div>
            <div
              class="terminal-pane"
              [class.active-pane]="
                pane.id === activePaneId && tab.id === activeTabId
              "
              [style.flex]="pane.widthPercent + ' 1 0'"
              (click)="onPaneClick(tab.id, pane.id)"
            >
              <button
                *ngIf="tab.panes.length > 1"
                class="pane-close-btn"
                (click)="closePane(tab.id, pane.id); $event.stopPropagation()"
                title="Close pane"
              >
                &times;
              </button>
              <cli
                [options]="options"
                [height]="terminalHeight"
                [modules]="modules"
                [processors]="processors"
                [snapshot]="pane.snapshot"
              />
            </div>
          </ng-container>
        </div>
      </div>
    </div>
  </ng-container>
</collapsable-content>

<!-- Context menu rendered outside collapsable-content to escape transform/overflow clipping -->
<div
  class="tab-context-menu"
  *ngIf="contextMenu.visible"
  [style.left.px]="contextMenu.x"
  [style.top.px]="contextMenu.y"
  (click)="$event.stopPropagation()"
>
  <button class="context-menu-item" (click)="contextMenuRename()">
    Rename
  </button>
  <button class="context-menu-item" (click)="contextMenuDuplicate()">
    Duplicate
  </button>
  <button class="context-menu-item" (click)="contextMenuSplitRight()">
    Split Right
  </button>
  <div class="context-menu-separator"></div>
  <button class="context-menu-item" (click)="contextMenuClose()">Close</button>
  <button
    class="context-menu-item"
    (click)="contextMenuCloseOthers()"
    [disabled]="tabs.length <= 1"
  >
    Close Others
  </button>
  <button class="context-menu-item" (click)="contextMenuCloseToTheRight()">
    Close to the Right
  </button>
  <div class="context-menu-separator"></div>
  <button class="context-menu-item destructive" (click)="contextMenuCloseAll()">
    Close All
  </button>
</div>

// packages/react-cli/src/CliPanel.tsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import { ICliCommandProcessor, ICliModule, CliPanelConfig } from '@qodalis/cli-core';
import { CliEngineOptions } from '@qodalis/cli';
import { Cli } from './Cli';
import { CliContext } from './CliContext';
import { useCliConfig } from './CliConfigContext';

export interface CliPanelOptions extends CliEngineOptions, CliPanelConfig {}

export interface CliPanelProps {
    options?: CliPanelOptions;
    modules?: ICliModule[];
    processors?: ICliCommandProcessor[];
    services?: Record<string, any>;
    onClose?: () => void;
    style?: React.CSSProperties;
    className?: string;
}

interface TerminalPane {
    id: number;
    widthPercent: number;
}

interface TerminalTab {
    id: number;
    title: string;
    isEditing: boolean;
    panes: TerminalPane[];
}

interface TabContextMenu {
    visible: boolean;
    x: number;
    y: number;
    tabId: number;
}

const MIN_PANE_WIDTH_PERCENT = 10;

/* ─── SVG icons ──────────────────────────────────────────── */

const TerminalIcon = () => (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="4 17 10 11 4 5" />
        <line x1="12" y1="19" x2="20" y2="19" />
    </svg>
);

const MaximizeIcon = () => (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="15 3 21 3 21 9" />
        <polyline points="9 21 3 21 3 15" />
        <line x1="21" y1="3" x2="14" y2="10" />
        <line x1="3" y1="21" x2="10" y2="14" />
    </svg>
);

const RestoreIcon = () => (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="4 14 10 14 10 20" />
        <polyline points="20 10 14 10 14 4" />
        <line x1="14" y1="10" x2="21" y2="3" />
        <line x1="3" y1="21" x2="10" y2="14" />
    </svg>
);

const CloseIcon = () => (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <line x1="18" y1="6" x2="6" y2="18" />
        <line x1="6" y1="6" x2="18" y2="18" />
    </svg>
);

function CollapseChevron({ position, isCollapsed }: { position: string; isCollapsed: boolean }) {
    let points: string;
    switch (position) {
        case 'top':
            points = isCollapsed ? '6 9 12 15 18 9' : '18 15 12 9 6 15';
            break;
        case 'left':
            points = isCollapsed ? '9 18 15 12 9 6' : '15 6 9 12 15 18';
            break;
        case 'right':
            points = isCollapsed ? '15 6 9 12 15 18' : '9 18 15 12 9 6';
            break;
        default: // bottom
            points = isCollapsed ? '18 15 12 9 6 15' : '6 9 12 15 18 9';
            break;
    }
    return (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
            <polyline points={points} />
        </svg>
    );
}

/* ─── Component ──────────────────────────────────────────── */

export function CliPanel({ options: optionsProp, modules: modulesProp, processors: processorsProp, services: servicesProp, onClose, style, className }: CliPanelProps) {
    const config = useCliConfig();
    const options = optionsProp ?? config.options as CliPanelOptions | undefined;
    const modules = modulesProp ?? config.modules;
    const processors = processorsProp ?? config.processors;
    const services = servicesProp ?? config.services;

    const position = options?.position ?? 'bottom';
    const closable = options?.closable ?? true;
    const resizable = options?.resizable ?? true;
    const isHorizontal = position === 'left' || position === 'right';

    const [visible, setVisible] = useState(true);
    const [collapsed, setCollapsed] = useState(options?.isCollapsed ?? true);
    const [maximized, setMaximized] = useState(false);
    const [panelHeight, setPanelHeight] = useState(600);
    const [panelWidth, setPanelWidth] = useState(400);
    const [initialized, setInitialized] = useState(false);

    const [tabs, setTabs] = useState<TerminalTab[]>([]);
    const [activeTabId, setActiveTabId] = useState(0);
    const [activePaneId, setActivePaneId] = useState(0);
    const nextIdRef = useRef({ tab: 1, pane: 1 });

    const [contextMenu, setContextMenu] = useState<TabContextMenu>({ visible: false, x: 0, y: 0, tabId: 0 });

    // Pane resize state
    const [paneResizing, setPaneResizing] = useState(false);
    const paneResizeRef = useRef({ tabId: 0, dividerIndex: 0, startX: 0, startWidths: [] as number[], containerWidth: 0 });

    // Panel resize state
    const [panelResizing, setPanelResizing] = useState(false);
    const panelResizeRef = useRef({ startY: 0, startHeight: 0, startX: 0, startWidth: 0 });
    const prevHeightRef = useRef(600);
    const prevWidthRef = useRef(400);

    // Terminal height is handled via CSS flex layout (height: 100% default in Cli)

    /* ─── Tab management ─────────────────────────────────── */

    const addTab = useCallback(() => {
        const paneId = nextIdRef.current.pane++;
        const tabId = nextIdRef.current.tab++;
        const pane: TerminalPane = { id: paneId, widthPercent: 100 };
        const tab: TerminalTab = { id: tabId, title: `Terminal ${tabId}`, isEditing: false, panes: [pane] };
        setTabs(prev => [...prev, tab]);
        setActiveTabId(tabId);
        setActivePaneId(paneId);
    }, []);

    const toggle = useCallback(() => {
        setCollapsed(prev => {
            const next = !prev;
            if (!next && !initialized) {
                setInitialized(true);
                // Add first tab
                const paneId = nextIdRef.current.pane++;
                const tabId = nextIdRef.current.tab++;
                const pane: TerminalPane = { id: paneId, widthPercent: 100 };
                const tab: TerminalTab = { id: tabId, title: `Terminal ${tabId}`, isEditing: false, panes: [pane] };
                setTabs([tab]);
                setActiveTabId(tabId);
                setActivePaneId(paneId);
            }
            return next;
        });
    }, [initialized]);

    const closeTab = useCallback((id: number) => {
        setTabs(prev => {
            const next = prev.filter(t => t.id !== id);
            if (next.length === 0) {
                setInitialized(false);
                setCollapsed(true);
                return [];
            }
            setActiveTabId(current => {
                if (current === id) {
                    const oldIdx = prev.findIndex(t => t.id === id);
                    const newIdx = Math.min(oldIdx, next.length - 1);
                    return next[newIdx].id;
                }
                return current;
            });
            return next;
        });
    }, []);

    const selectTab = useCallback((id: number) => {
        setActiveTabId(id);
        setTabs(prev => {
            const tab = prev.find(t => t.id === id);
            if (tab && tab.panes.length > 0) {
                setActivePaneId(tab.panes[0].id);
            }
            return prev;
        });
    }, []);

    /* ─── Split / close pane ─────────────────────────────── */

    const normalizePanes = (panes: TerminalPane[]) => {
        const total = panes.reduce((s, p) => s + p.widthPercent, 0);
        if (total === 0) return;
        const scale = 100 / total;
        panes.forEach(p => { p.widthPercent *= scale; });
    };

    const splitRight = useCallback((tabId?: number, afterPaneId?: number) => {
        setTabs(prev => {
            const next = prev.map(t => ({ ...t, panes: t.panes.map(p => ({ ...p })) }));
            const tab = next.find(t => t.id === (tabId ?? activeTabId));
            if (!tab) return prev;

            const targetPaneId = afterPaneId ?? activePaneId;
            const idx = tab.panes.findIndex(p => p.id === targetPaneId);
            const insertIdx = idx === -1 ? tab.panes.length : idx + 1;

            const newPaneId = nextIdRef.current.pane++;
            const newPane: TerminalPane = { id: newPaneId, widthPercent: 0 };
            tab.panes.splice(insertIdx, 0, newPane);

            const evenWidth = 100 / tab.panes.length;
            tab.panes.forEach(p => { p.widthPercent = evenWidth; });
            normalizePanes(tab.panes);

            setActivePaneId(newPaneId);
            return next;
        });
    }, [activeTabId, activePaneId]);

    const closePane = useCallback((tabId: number, paneId: number) => {
        setTabs(prev => {
            const tab = prev.find(t => t.id === tabId);
            if (!tab) return prev;

            if (tab.panes.length <= 1) {
                const next = prev.filter(t => t.id !== tabId);
                if (next.length === 0) {
                    setInitialized(false);
                    setCollapsed(true);
                    return [];
                }
                return next;
            }

            const next = prev.map(t => ({ ...t, panes: t.panes.map(p => ({ ...p })) }));
            const updatedTab = next.find(t => t.id === tabId)!;
            const idx = updatedTab.panes.findIndex(p => p.id === paneId);
            if (idx === -1) return prev;

            updatedTab.panes.splice(idx, 1);
            const totalRemaining = updatedTab.panes.reduce((s, p) => s + p.widthPercent, 0);
            if (totalRemaining > 0) {
                updatedTab.panes.forEach(p => { p.widthPercent = (p.widthPercent / totalRemaining) * 100; });
            }
            normalizePanes(updatedTab.panes);

            setActivePaneId(curr => {
                if (curr === paneId) {
                    const newIdx = Math.min(idx, updatedTab.panes.length - 1);
                    return updatedTab.panes[newIdx].id;
                }
                return curr;
            });
            return next;
        });
    }, []);

    /* ─── Rename ─────────────────────────────────────────── */

    const startRename = useCallback((tabId: number) => {
        setTabs(prev => prev.map(t => ({ ...t, isEditing: t.id === tabId })));
    }, []);

    const commitRename = useCallback((tabId: number, value: string) => {
        const trimmed = value.trim();
        setTabs(prev => prev.map(t =>
            t.id === tabId ? { ...t, title: trimmed || t.title, isEditing: false } : t,
        ));
    }, []);

    /* ─── Context menu ───────────────────────────────────── */

    const closeContextMenu = useCallback(() => {
        setContextMenu(prev => ({ ...prev, visible: false }));
    }, []);

    useEffect(() => {
        if (!contextMenu.visible) return;
        const handler = () => closeContextMenu();
        document.addEventListener('click', handler);
        return () => document.removeEventListener('click', handler);
    }, [contextMenu.visible, closeContextMenu]);

    /* ─── Panel resize ───────────────────────────────────── */

    const onPanelResizeStart = useCallback((e: React.MouseEvent) => {
        if (!resizable) return;
        e.preventDefault();
        if (collapsed) {
            toggle();
        }
        setPanelResizing(true);
        panelResizeRef.current = {
            startY: e.clientY,
            startHeight: panelHeight,
            startX: e.clientX,
            startWidth: panelWidth,
        };
    }, [collapsed, toggle, panelHeight, panelWidth, resizable]);

    useEffect(() => {
        if (!panelResizing) return;
        const onMove = (e: MouseEvent) => {
            if (isHorizontal) {
                const deltaX = position === 'left'
                    ? e.clientX - panelResizeRef.current.startX
                    : panelResizeRef.current.startX - e.clientX;
                let next = Math.max(100, panelResizeRef.current.startWidth + deltaX);
                if (next > window.innerWidth) next = window.innerWidth;
                setPanelWidth(next);
            } else {
                const deltaY = position === 'top'
                    ? e.clientY - panelResizeRef.current.startY
                    : panelResizeRef.current.startY - e.clientY;
                let next = Math.max(100, panelResizeRef.current.startHeight + deltaY);
                if (next > window.innerHeight) next = window.innerHeight;
                setPanelHeight(next);
            }
        };
        const onUp = () => setPanelResizing(false);
        document.addEventListener('mousemove', onMove);
        document.addEventListener('mouseup', onUp);
        return () => { document.removeEventListener('mousemove', onMove); document.removeEventListener('mouseup', onUp); };
    }, [panelResizing, isHorizontal, position]);

    /* ─── Pane resize ────────────────────────────────────── */

    const onPaneResizeStart = useCallback((e: React.MouseEvent, tabId: number, dividerIndex: number) => {
        e.preventDefault();
        const tab = tabs.find(t => t.id === tabId);
        if (!tab) return;
        setPaneResizing(true);
        const container = (e.target as HTMLElement).closest('.cli-panel-panes-container');
        paneResizeRef.current = {
            tabId,
            dividerIndex,
            startX: e.clientX,
            startWidths: tab.panes.map(p => p.widthPercent),
            containerWidth: container ? container.clientWidth : 1,
        };
    }, [tabs]);

    useEffect(() => {
        if (!paneResizing) return;
        const onMove = (e: MouseEvent) => {
            const ref = paneResizeRef.current;
            const deltaX = e.clientX - ref.startX;
            const deltaPct = (deltaX / ref.containerWidth) * 100;
            const i = ref.dividerIndex;

            let leftWidth = ref.startWidths[i] + deltaPct;
            let rightWidth = ref.startWidths[i + 1] - deltaPct;

            if (leftWidth < MIN_PANE_WIDTH_PERCENT) {
                leftWidth = MIN_PANE_WIDTH_PERCENT;
                rightWidth = ref.startWidths[i] + ref.startWidths[i + 1] - MIN_PANE_WIDTH_PERCENT;
            }
            if (rightWidth < MIN_PANE_WIDTH_PERCENT) {
                rightWidth = MIN_PANE_WIDTH_PERCENT;
                leftWidth = ref.startWidths[i] + ref.startWidths[i + 1] - MIN_PANE_WIDTH_PERCENT;
            }

            setTabs(prev => {
                const next = prev.map(t => ({ ...t, panes: t.panes.map(p => ({ ...p })) }));
                const tab = next.find(t => t.id === ref.tabId);
                if (tab) {
                    tab.panes[i].widthPercent = leftWidth;
                    tab.panes[i + 1].widthPercent = rightWidth;
                }
                return next;
            });
        };
        const onUp = () => {
            setPaneResizing(false);
            document.body.classList.remove('cli-pane-resizing');
        };
        document.body.classList.add('cli-pane-resizing');
        document.addEventListener('mousemove', onMove);
        document.addEventListener('mouseup', onUp);
        return () => { document.removeEventListener('mousemove', onMove); document.removeEventListener('mouseup', onUp); };
    }, [paneResizing]);

    /* ─── Maximize ───────────────────────────────────────── */

    const toggleMaximize = useCallback(() => {
        setMaximized(prev => {
            if (!prev) {
                if (isHorizontal) {
                    prevWidthRef.current = panelWidth;
                    setPanelWidth(window.innerWidth);
                } else {
                    prevHeightRef.current = panelHeight;
                    setPanelHeight(window.innerHeight);
                }
            } else {
                if (isHorizontal) {
                    setPanelWidth(prevWidthRef.current);
                } else {
                    setPanelHeight(prevHeightRef.current);
                }
            }
            return !prev;
        });
    }, [panelHeight, panelWidth, isHorizontal]);

    /* ─── Close handler ──────────────────────────────────── */

    const handleClose = useCallback(() => {
        setVisible(false);
        onClose?.();
    }, [onClose]);

    /* ─── Render ─────────────────────────────────────────── */

    if (!visible) return null;

    const wrapperStyle: React.CSSProperties = isHorizontal
        ? { width: `${panelWidth}px`, ...style }
        : { height: `${panelHeight}px`, ...style };

    return (
        <>
            <div
                className={`cli-panel-wrapper ${collapsed ? 'collapsed' : ''} ${maximized ? 'maximized' : ''} ${panelResizing ? 'resizing' : ''} ${className ?? ''}`}
                style={wrapperStyle}
                data-position={position}
                data-resizable={String(resizable)}
                data-closable={String(closable)}
            >
                {/* Header */}
                <div className="cli-panel-header">
                    <div className="cli-panel-resize-bar" onMouseDown={onPanelResizeStart}>
                        <div className="cli-panel-resize-grip" />
                    </div>
                    <div className="cli-panel-header-content">
                        <p className="cli-panel-title">
                            <span className="cli-panel-title-icon"><TerminalIcon /></span>
                            CLI
                        </p>
                        <div className="cli-panel-action-buttons">
                            <button className="cli-panel-btn" title={maximized ? 'Restore' : 'Maximize'} disabled={collapsed} onClick={toggleMaximize}>
                                {maximized ? <RestoreIcon /> : <MaximizeIcon />}
                            </button>
                            <button className="cli-panel-btn" title={collapsed ? 'Expand' : 'Collapse'} onClick={toggle}>
                                <CollapseChevron position={position} isCollapsed={collapsed} />
                            </button>
                            {closable && (
                                <button className="cli-panel-btn cli-panel-btn-close" title="Close" onClick={handleClose}>
                                    <CloseIcon />
                                </button>
                            )}
                        </div>
                    </div>
                </div>

                {/* Content */}
                {!collapsed && initialized && (
                    <div className="cli-panel-content">
                        {/* Tab bar */}
                        <div className="cli-panel-tabs">
                            <ul className="cli-panel-tab-list">
                                {tabs.map(tab => (
                                    <li
                                        key={tab.id}
                                        className={`cli-panel-tab ${tab.id === activeTabId ? 'active' : ''}`}
                                        onClick={() => selectTab(tab.id)}
                                        onDoubleClick={() => startRename(tab.id)}
                                        onContextMenu={e => {
                                            e.preventDefault();
                                            e.stopPropagation();
                                            setContextMenu({ visible: true, x: e.clientX, y: e.clientY, tabId: tab.id });
                                        }}
                                    >
                                        {tab.isEditing ? (
                                            <input
                                                className="cli-panel-tab-rename-input"
                                                type="text"
                                                defaultValue={tab.title}
                                                autoFocus
                                                onKeyDown={e => {
                                                    if (e.key === 'Enter') commitRename(tab.id, (e.target as HTMLInputElement).value);
                                                    else if (e.key === 'Escape') setTabs(prev => prev.map(t => ({ ...t, isEditing: false })));
                                                }}
                                                onBlur={e => commitRename(tab.id, e.target.value)}
                                                onClick={e => e.stopPropagation()}
                                                onDoubleClick={e => e.stopPropagation()}
                                            />
                                        ) : (
                                            <>
                                                <span className="cli-panel-tab-title">{tab.title}</span>
                                                <button
                                                    className="cli-panel-tab-close-btn"
                                                    title="Close tab"
                                                    onClick={e => { e.stopPropagation(); closeTab(tab.id); }}
                                                >&times;</button>
                                            </>
                                        )}
                                    </li>
                                ))}
                            </ul>
                            <button className="cli-panel-add-tab" title="New terminal" onClick={addTab}>+</button>
                        </div>

                        {/* Terminal instances */}
                        <div className="cli-panel-instances">
                            {tabs.map(tab => (
                                <div key={tab.id} className="cli-panel-instance" style={{ display: tab.id === activeTabId ? undefined : 'none' }}>
                                    <div className={`cli-panel-panes-container ${paneResizing ? 'resizing' : ''}`}>
                                        {tab.panes.map((pane, i) => (
                                            <React.Fragment key={pane.id}>
                                                {i > 0 && (
                                                    <div className="cli-panel-pane-divider" onMouseDown={e => onPaneResizeStart(e, tab.id, i - 1)}>
                                                        <div className="cli-panel-pane-divider-grip" />
                                                    </div>
                                                )}
                                                <div
                                                    className={`cli-panel-pane ${pane.id === activePaneId && tab.id === activeTabId ? 'active-pane' : ''}`}
                                                    style={{ flex: `${pane.widthPercent} 1 0` }}
                                                    onClick={() => { setActivePaneId(pane.id); setActiveTabId(tab.id); }}
                                                >
                                                    {tab.panes.length > 1 && (
                                                        <button
                                                            className="cli-panel-pane-close-btn"
                                                            onClick={e => { e.stopPropagation(); closePane(tab.id, pane.id); }}
                                                            title="Close pane"
                                                        >&times;</button>
                                                    )}
                                                    <CliContext.Provider value={{ engine: null }}>
                                                        <Cli options={options} modules={modules} processors={processors} services={services} />
                                                    </CliContext.Provider>
                                                </div>
                                            </React.Fragment>
                                        ))}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}
            </div>

            {/* Context menu */}
            {contextMenu.visible && (
                <div
                    className="cli-panel-context-menu"
                    style={{ left: contextMenu.x, top: contextMenu.y }}
                    onClick={e => e.stopPropagation()}
                >
                    <button className="cli-panel-context-menu-item" onClick={() => { closeContextMenu(); startRename(contextMenu.tabId); }}>Rename</button>
                    <button className="cli-panel-context-menu-item" onClick={() => {
                        closeContextMenu();
                        const tab = tabs.find(t => t.id === contextMenu.tabId);
                        if (!tab) return;
                        const paneId = nextIdRef.current.pane++;
                        const tabId = nextIdRef.current.tab++;
                        const pane: TerminalPane = { id: paneId, widthPercent: 100 };
                        const newTab: TerminalTab = { id: tabId, title: `${tab.title} (copy)`, isEditing: false, panes: [pane] };
                        const idx = tabs.indexOf(tab);
                        setTabs(prev => { const next = [...prev]; next.splice(idx + 1, 0, newTab); return next; });
                        setActiveTabId(tabId);
                        setActivePaneId(paneId);
                    }}>Duplicate</button>
                    <button className="cli-panel-context-menu-item" onClick={() => { closeContextMenu(); splitRight(contextMenu.tabId); }}>Split Right</button>
                    <div className="cli-panel-context-menu-separator" />
                    <button className="cli-panel-context-menu-item" onClick={() => { closeContextMenu(); closeTab(contextMenu.tabId); }}>Close</button>
                    <button className="cli-panel-context-menu-item" disabled={tabs.length <= 1} onClick={() => { closeContextMenu(); setTabs(prev => prev.filter(t => t.id === contextMenu.tabId)); setActiveTabId(contextMenu.tabId); }}>Close Others</button>
                    <button className="cli-panel-context-menu-item" onClick={() => {
                        const id = contextMenu.tabId;
                        closeContextMenu();
                        setTabs(prev => {
                            const idx = prev.findIndex(t => t.id === id);
                            if (idx === -1) return prev;
                            return prev.slice(0, idx + 1);
                        });
                    }}>Close to the Right</button>
                    <div className="cli-panel-context-menu-separator" />
                    <button className="cli-panel-context-menu-item destructive" onClick={() => { closeContextMenu(); setTabs([]); setInitialized(false); setCollapsed(true); }}>Close All</button>
                </div>
            )}
        </>
    );
}
